services:
  # PostgreSQL DB
  database:
    image: sheikah-slate-bot/db
    container_name: sheikah-slate-bot_db
    env_file: './packages/db/.env'
    build:
      dockerfile: ./packages/db/Dockerfile.db
    volumes:
      - app-db-data:/var/lib/postgresql/data
    networks:
      - app-network-public
      - app-network-internal

  # Simple service to wait for DB setup
  database-wait:
    image: atkrad/wait4x
    container_name: sheikah-slate-bot_db-wait
    depends_on:
      - database
    networks:
      - app-network-public
      - app-network-internal
    command: tcp database:5432 -t 30s -i 250ms

  # DB Migrations
  database-migrations:
    image: sheikah-slate-bot/db-migrations
    container_name: sheikah-slate-bot_db-migrations
    env_file: './packages/db/.env'
    build:
      dockerfile: ./packages/db/Dockerfile.migrations
    depends_on:
      database-wait:
        condition: service_completed_successfully
    networks:
      - app-network-public
      - app-network-internal

  # API Service
  api-public:
    image: sheikah-slate-bot/api/public
    container_name: sheikah-slate-bot_api-public
    build:
      dockerfile: ./packages/api/Dockerfile.public
    depends_on:
      database-migrations:
        condition: service_completed_successfully
    networks:
      - app-network-public

  api-internal:
    image: sheikah-slate-bot/api/internal
    container_name: sheikah-slate-bot_api-internal
    build:
      dockerfile: ./packages/api/Dockerfile.internal
    depends_on:
      database-migrations:
        condition: service_completed_successfully
    networks:
      - app-network-internal

  # Discord Bot
  discord-bot:
    image: sheikah-slate-bot/discord-bot
    container_name: sheikah-slate-bot_discord-bot
    build:
      dockerfile: ./packages/discord-bot/Dockerfile
    depends_on:
      - api-internal
    networks:
      - app-network-internal

  # Twitch Bot
  twitch-bot:
    image: sheikah-slate-bot/twitch-bot
    container_name: sheikah-slate-bot_twitch-bot
    build:
      dockerfile: ./packages/twitch-bot/Dockerfile
    depends_on:
      - api-internal
    networks:
      - app-network-internal

networks:
  app-network-public:
    name: sheikah-slate-bot_network-public
  app-network-internal:
    name: sheikah-slate-bot_network-internal

volumes:
  app-db-data:
    name: sheikah-slate-bot_db-data
